import {test,before} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';

// Exercise the actual route handler with SQLite and R2-shaped storage.
// Only Cloudflare bindings and outbound HTTP are replaced in this test process.
const tmp=new URL('../.test-build/',import.meta.url);mkdirSync(tmp,{recursive:true});
for(const file of ['domain','schedule','server']){let source=readFileSync(new URL('../lib/'+file+'.ts',import.meta.url),'utf8').replace("import {env} from 'cloudflare:workers';","const env=globalThis.__testEnv;").replace("from './domain'","from './domain.mjs'").replace("from './schedule'","from './schedule.mjs'");writeFileSync(new URL(file+'.mjs',tmp),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);}
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../drizzle/0000_open_the_hood.sql',import.meta.url),'utf8'));
const DB={prepare(sql){let values=[];const query={bind(...args){values=args;return query;},async first(){return db.prepare(sql).get(...values)||null;},async all(){return {results:db.prepare(sql).all(...values)};},async run(){const result=db.prepare(sql).run(...values);return {meta:{changes:Number(result.changes)}};}};return query;},async batch(queries){return Promise.all(queries.map(q=>q.run()));}};
const objects=new Map(),BUCKET={async put(key,value){objects.set(key,new Uint8Array(value));},async get(key){const value=objects.get(key);return value?{body:value,arrayBuffer:async()=>value.buffer.slice(value.byteOffset,value.byteOffset+value.byteLength)}:null;},async delete(key){objects.delete(key);}};
globalThis.__testEnv={DB,BUCKET};const {handle}=await import(pathToFileURL(new URL('server.mjs',tmp).pathname));
const {protectSchedule}=await import(new URL('schedule.mjs',tmp));
const profile={name:'测试用户',roles:'研究者',goals:'完成论文',health:'保持规律',appearance:'舒服的穿搭',start:'09:00',end:'20:00',tone:'gentle',aiConsent:false};
const task={title:'写作',role:'work',date:'2026-10-01',duration:60,priority:3,time:'10:00',notes:'',done:false};
async function request(path,method='GET',data,owner='alice',extra={}){const headers={'oai-authenticated-user-id':owner,'origin':'https://test.example',...extra};if(!owner)delete headers['oai-authenticated-user-id'];const body=data instanceof FormData?data:data===undefined?undefined:JSON.stringify(data);if(body&&!(data instanceof FormData))headers['content-type']='application/json';const r=await handle(new Request('https://test.example/api/'+path,{method,headers,body}));return {status:r.status,data:(r.headers.get('content-type')||'').includes('json')?await r.json():await r.arrayBuffer(),headers:r.headers};}
test('anonymous users and cross-site mutations are rejected',async()=>{assert.equal((await request('bootstrap','GET',undefined,'')).status,401);assert.equal((await request('records','PUT',{},'alice',{origin:'https://evil.example'})).status,403);});
test('profile persists and records are isolated by owner',async()=>{const saved=await request('records','PUT',{id:'profile',kind:'profile',data:profile,revision:0});assert.equal(saved.status,200);assert.equal((await request('bootstrap')).data.records[0].data.name,'测试用户');assert.equal((await request('bootstrap','GET',undefined,'bob')).data.records.length,0);assert.equal((await request('records/profile','DELETE',undefined,'bob')).status,404);});
test('stale updates cannot overwrite newer data',async()=>{const stale=await request('records','PUT',{id:'profile',kind:'profile',data:{...profile,name:'stale'},revision:0});assert.equal(stale.status,409);assert.equal((await request('bootstrap')).data.records[0].data.name,'测试用户');});
test('invalid calendar date and overnight tasks fail validation',async()=>{assert.equal((await request('records','PUT',{id:'bad',kind:'task',data:{...task,date:'2026-02-30'},revision:0})).status,400);assert.equal((await request('records','PUT',{id:'bad',kind:'task',data:{...task,time:'23:45'},revision:0})).status,400);});
let photo;
test('photos require a supported signature and cannot be read by another user',async()=>{const invalid=new FormData();invalid.set('file',new File(['<svg>'],'x.jpg',{type:'image/jpeg'}));invalid.set('date','2026-10-01');assert.equal((await request('photos','POST',invalid)).status,400);const valid=new FormData();valid.set('file',new File([new Uint8Array([255,216,255,0,1])],'x.jpg',{type:'image/jpeg'}));valid.set('date','2026-10-01');const out=await request('photos','POST',valid);assert.equal(out.status,200);photo=out.data.record;assert.equal(photo.data.key,undefined);assert.equal((await request('photos/'+photo.id)).status,200);assert.equal((await request('photos/'+photo.id,'GET',undefined,'bob')).status,404);assert.match((await request('photos/'+photo.id)).headers.get('cache-control'),/no-store/);});
const chatId=crypto.randomUUID();
test('unconfigured AI saves the message without fabricating a response',async()=>{const out=await request('chat','POST',{id:chatId,text:'陪我聊聊',date:'2026-10-01',photoIds:[photo.id]});assert.equal(out.status,200);assert.equal(out.data.aiReady,false);const entries=(await request('bootstrap')).data.records;assert.equal(entries.filter(r=>r.kind==='message').length,1);assert.equal(entries.find(r=>r.id===chatId).data.role,'user');});
test('AI data sharing requires consent',async()=>{globalThis.__testEnv.OPENAI_API_KEY='test-placeholder';const out=await request('chat','POST',{id:chatId,text:'陪我聊聊',date:'2026-10-01'});assert.equal(out.data.needsConsent,true);});
test('structured model response creates tasks, keeps memories optional and is idempotent',async()=>{await request('records','PUT',{id:'profile',kind:'profile',data:{...profile,aiConsent:true},revision:1});const priorFetch=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/responses');const payload=JSON.parse(options.body);assert.equal(payload.store,false);assert.equal(payload.input.at(-1).content.some(c=>c.type==='input_image'),false);return Response.json({output:[{content:[{type:'output_text',text:JSON.stringify({reply:'这是你可以调整的计划。',tasks:[task],memories:[{title:'规律作息',content:'希望规律生活',role:'health',type:'preference',source:'对话'}]})}]}]});};try{const input={id:chatId,text:'陪我聊聊',date:'2026-10-01',mode:'plan',photoIds:[photo.id],analyzePhotos:false};assert.equal((await request('chat','POST',input)).status,200);assert.equal((await request('chat','POST',input)).status,200);assert.equal(calls,1);const entries=(await request('bootstrap')).data.records;assert.equal(entries.filter(r=>r.kind==='task').length,1);assert.equal(entries.filter(r=>r.kind==='memory').length,0);assert.equal(entries.filter(r=>r.kind==='message'&&r.data.role==='assistant').length,1);}finally{globalThis.fetch=priorFetch;}});
test('model suggested fixed times cannot introduce new overlaps or exceed the available day',()=>{const existing=[{kind:'task',data:task}];const out=protectSchedule([{...task,time:'10:30'},{...task,time:'22:00'},{...task,time:'12:00'},{...task,time:'12:30'}],existing,profile);assert.deepEqual(out.map(t=>t.time),['','','12:00','']);assert.ok(out.every(t=>t.done===false));});
test('photo deletion removes private bytes and references from messages',async()=>{assert.equal((await request('records/'+photo.id,'DELETE')).status,200);assert.equal(objects.size,0);const entries=(await request('bootstrap')).data.records;assert.deepEqual(entries.find(r=>r.id===chatId).data.photoIds,[]);assert.equal((await request('photos/'+photo.id)).status,404);});
test('delete all is restricted to the current owner',async()=>{await request('records','PUT',{id:'profile',kind:'profile',data:profile,revision:0},'bob');assert.equal((await request('everything','DELETE')).status,200);assert.equal((await request('bootstrap')).data.records.length,0);assert.equal((await request('bootstrap','GET',undefined,'bob')).data.records.length,1);});
process.on('exit',()=>{db.close();rmSync(tmp,{recursive:true,force:true});});
