import { z } from 'zod';
export const kinds=['profile','message','task','memory','checkin','photo','connection','activity'] as const;
export type Kind=typeof kinds[number];
export type Entry={id:string;kind:Kind;data:Record<string,any>;createdAt:string;updatedAt:string;revision:number};
export const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const d=new Date(v+'T12:00:00Z');return !isNaN(d.valueOf())&&d.toISOString().slice(0,10)===v;},'日期无效');
const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
export const profileSchema=z.object({name:z.string().trim().min(1).max(40),roles:z.string().max(200),goals:z.string().max(1500),health:z.string().max(1000),appearance:z.string().max(1000),start:time,end:time,tone:z.enum(['gentle','direct','brief']),aiConsent:z.boolean()}).refine(p=>p.end>p.start,'结束时间应晚于开始时间');
export const taskSchema=z.object({title:z.string().trim().min(1).max(160),role:z.enum(['work','family','health','self']),date:day,duration:z.number().int().min(5).max(240),priority:z.number().int().min(1).max(3),time:z.union([time,z.literal('')]),notes:z.string().max(1000).default(''),done:z.boolean().default(false)}).refine(t=>!t.time||(Number(t.time.slice(0,2))*60+Number(t.time.slice(3))+t.duration<=1440),'任务不能跨越午夜');
export const memorySchema=z.object({title:z.string().trim().min(1).max(160),content:z.string().trim().min(1).max(4000),role:z.enum(['work','family','health','self']).default('self'),type:z.enum(['fact','preference','insight']).default('fact'),source:z.string().max(160).default('我的记录')});
export const checkinSchema=z.object({date:day,mood:z.number().int().min(1).max(5),energy:z.number().int().min(1).max(5),sleep:z.number().min(0).max(24).nullable(),movement:z.number().int().min(0).max(1440).nullable(),note:z.string().max(3000)});
export const recordInput=z.object({id:z.string().regex(/^[A-Za-z0-9:_-]{1,180}$/),kind:z.enum(['profile','task','memory','checkin']),data:z.unknown(),revision:z.number().int().min(0).default(0)});
export function parseRecord(kind:string,data:unknown){if(kind==='profile')return profileSchema.parse(data);if(kind==='task')return taskSchema.parse(data);if(kind==='memory')return memorySchema.parse(data);if(kind==='checkin')return checkinSchema.parse(data);throw Error('不支持的记录类型');}
export const chatInput=z.object({id:z.string().uuid(),text:z.string().max(6000),date:day,mode:z.enum(['chat','plan']).default('chat'),photoIds:z.array(z.string().uuid()).max(2).default([]),analyzePhotos:z.boolean().default(false)}).refine(v=>v.text.trim()||v.photoIds.length,'请写点内容或添加照片');
export const replySchema=z.object({reply:z.string().min(1).max(12000),tasks:z.array(taskSchema).max(8),memories:z.array(memorySchema).max(3)});
export const replyJsonSchema={type:'object',additionalProperties:false,properties:{reply:{type:'string'},tasks:{type:'array',items:{type:'object',additionalProperties:false,properties:{title:{type:'string'},role:{type:'string',enum:['work','family','health','self']},date:{type:'string'},duration:{type:'integer'},priority:{type:'integer'},time:{type:'string'},notes:{type:'string'},done:{type:'boolean'}},required:['title','role','date','duration','priority','time','notes','done']}},memories:{type:'array',items:{type:'object',additionalProperties:false,properties:{title:{type:'string'},content:{type:'string'},role:{type:'string',enum:['work','family','health','self']},type:{type:'string',enum:['fact','preference','insight']},source:{type:'string'}},required:['title','content','role','type','source']}}},required:['reply','tasks','memories']};
export function photoType(b:Uint8Array){if(b[0]===255&&b[1]===216&&b[2]===255)return 'image/jpeg';if([137,80,78,71,13,10,26,10].every((v,i)=>b[i]===v))return 'image/png';if(new TextDecoder().decode(b.slice(0,4))==='RIFF'&&new TextDecoder().decode(b.slice(8,12))==='WEBP')return 'image/webp';return null;}
